// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.21.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Author struct {
	ID   int64       `json:"id"`
	Name string      `json:"name"`
	Bio  pgtype.Text `json:"bio"`
}

type Tmp struct {
	ID        pgtype.Int8      `json:"id"`
	Title     pgtype.Text      `json:"title"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	IsDeleted pgtype.Bool      `json:"is_deleted"`
}
