version: '3'
services:
  tc_backend:
    build:
      context: ./go
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
    container_name: tc_backend
    hostname: tc_backend
    working_dir: /var/www/app
    volumes:
      - ../:/var/www/app
    command: "bash"
    tty: true
    ports:
      - "80:80"
    environment:
      GO111MODULE: "on"
      GOSUMDB: "off"
      DATABASE_URL: ${DATABASE_URL}
  tc_postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: tc_postgres
    hostname: tc_postgres
    ports:
      - '5488:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /pgdata
    volumes:
      - tc_postgres_pg_data:/pgdata
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql      

networks:
  default:
    external:
      name: tc_network

volumes:
  tc_postgres_pg_data:
    external:
      name: tc_postgres_pg_data
